import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { AuthProvider } from '@/contexts/auth-context';
import { CartProvider } from "@/contexts/cart-context";

import { Bowlby_One_SC, DM_Mono } from "next/font/google";
import "./globals.css";
import { Leva } from "leva";

const bowlby = Bowlby_One_SC({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-bowlby-sc",
  weight: "400",
});

const dmMono = DM_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-mono",
  weight: "500",
});

export const metadata: Metadata = {
  title: "SnowCraft",
  description: "A 3d-Enabled DirectGenerated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

      <html lang="en" suppressHydrationWarning>
        <body
          className={`${bowlby.variable} ${dmMono.variable} antialiased font-mono font-medium text-zinc-800`}
          suppressHydrationWarning
        >
          <AuthProvider>
            <CartProvider>
              <main className="relative">
                {children}
              </main>
            </CartProvider>
          </AuthProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
