

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/snowboard.glb components/Snowboard.tsx 
*/

import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'

export function Snowboard({ topTexture, bottomColor, sideColor = "#000000", ...props }) {
  const { nodes, materials } = useGLTF('/models/snowboard.glb')

  const topTex = useTexture(topTexture || "/textures/headboard.png");
  topTex.flipY = false; // Adjust if your texture appears upside down
  topTex.wrapS = THREE.RepeatWrapping;
  topTex.wrapT = THREE.RepeatWrapping;
  topTex.repeat.set(1, 1);
  topTex.anisotropy = 16;
  // topTex.rotation = -Math.PI / 2;

  // Adjust texture mapping if needed, or simply apply to material
  const topMaterial = new THREE.MeshStandardMaterial({
    map: topTex,
    roughness: 0.2,
    metalness: 0.6,
  });

  // const bottomMaterial = new THREE.MeshStandardMaterial({
  //   color: bottomColor || "#ff0000",
  //   roughness: 0.4,
  // });

  // const sideMaterial = new THREE.MeshStandardMaterial({
  //   color: sideColor,
  //   roughness: 0.5,
  // });


  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.012, 0]}>
        <mesh geometry={nodes.snowboard_rocker_1.geometry} material={topMaterial} />
        <mesh geometry={nodes.snowboard_rocker_2.geometry} material={topMaterial} />
        <mesh geometry={nodes.snowboard_rocker_3.geometry} material={topMaterial} />
        <mesh geometry={nodes.snowboard_rocker_4.geometry} material={topMaterial} />
      </group>
      {/* <group position={[0, 0.008, 0]}>
        <mesh geometry={nodes.snowboard_flat_1.geometry} material={materials.topMaterial} />
        <mesh geometry={nodes.snowboard_flat_2.geometry} material={materials.topMaterial} />
        <mesh geometry={nodes.snowboard_flat_3.geometry} material={materials.topMaterial} />
        <mesh geometry={nodes.snowboard_flat_4.geometry} material={materials.topMaterial} />
      </group>
      <group position={[0, 0.012, 0]}>
        <mesh geometry={nodes.snowboard_rocker_1.geometry} material={materials.topMaterial} />
        <mesh geometry={nodes.snowboard_rocker_2.geometry} material={materials.topMaterial} />
        <mesh geometry={nodes.snowboard_rocker_3.geometry} material={materials.topMaterial} />
        <mesh geometry={nodes.snowboard_rocker_4.geometry} material={materials.topMaterial} />
      </group> */}
    </group>
  )
}

useGLTF.preload('/models/snowboard.glb')
