/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/snowboard.glb components/Snowboard.tsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/snowboard.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.027, 0]}>
        <mesh geometry={nodes.snowboard_camber_1.geometry} material={materials.top_color} />
        <mesh geometry={nodes.snowboard_camber_2.geometry} material={materials.bot_color} />
        <mesh geometry={nodes.snowboard_camber_3.geometry} material={materials.side_color} />
        <mesh geometry={nodes.snowboard_camber_4.geometry} material={materials.side_color} />
      </group>
      <group position={[0, 0.008, 0]}>
        <mesh geometry={nodes.snowboard_flat_1.geometry} material={materials.top_color} />
        <mesh geometry={nodes.snowboard_flat_2.geometry} material={materials.bot_color} />
        <mesh geometry={nodes.snowboard_flat_3.geometry} material={materials.side_color} />
        <mesh geometry={nodes.snowboard_flat_4.geometry} material={materials.side_color} />
      </group>
      <group position={[0, 0.012, 0]}>
        <mesh geometry={nodes.snowboard_rocker_1.geometry} material={materials.top_color} />
        <mesh geometry={nodes.snowboard_rocker_2.geometry} material={materials.bot_color} />
        <mesh geometry={nodes.snowboard_rocker_3.geometry} material={materials.side_color} />
        <mesh geometry={nodes.snowboard_rocker_4.geometry} material={materials.side_color} />
      </group>
    </group>
  )
}

useGLTF.preload('/snowboard.glb')
