/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/snowboard_sharp.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/snowboard_sharp.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.snowboard_sharp_1.geometry} material={materials.top_color} />
      <mesh geometry={nodes.snowboard_sharp_2.geometry} material={materials.bot_color} />
      <mesh geometry={nodes.snowboard_sharp_3.geometry} material={materials.side_color} />
    </group>
  )
}

useGLTF.preload('/snowboard_sharp.glb')
